
//#define HANKAKU10_OFFS 0x20

#define M 1
#define v 0
#define bc(aa,bb,cc,dd,ee,ff,gg,hh) (\
(aa?0x01:0x00)+\
(bb?0x02:0x00)+\
(cc?0x04:0x00)+\
(dd?0x08:0x00)+\
(ee?0x10:0x00)+\
(ff?0x20:0x00)+\
(gg?0x40:0x00)+\
(hh?0x80:0x00)\
)

const unsigned char msx8[] = /* x:y == 5x10 */
{
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x00*/

bc(v,v,M,M,M,M,v,v),
bc(v,M,v,v,v,v,M,v),
bc(M,v,M,v,v,M,v,M),
bc(M,v,v,v,v,v,v,M),
bc(M,v,M,v,v,M,v,M),
bc(M,v,v,M,M,v,v,M),
bc(v,M,v,v,v,v,M,v),
bc(v,v,M,M,M,M,v,v),	/*0x01*/

bc(v,v,M,M,M,M,v,v),
bc(v,M,M,M,M,M,M,v),
bc(M,M,v,M,M,v,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,v,M,M,v,M,M),
bc(v,M,M,v,v,M,M,v),
bc(v,v,M,M,M,M,v,v),	/*0x02*/

bc(v,M,M,v,M,M,v,v),
bc(M,M,M,M,M,M,M,v),
bc(M,M,M,M,M,M,M,v),
bc(M,M,M,M,M,M,M,v),
bc(v,M,M,M,M,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x03*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,M,v),
bc(v,M,M,M,M,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x04*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,M,v,M,v,M,v,v),
bc(M,M,M,M,M,M,M,v),
bc(v,M,v,M,v,M,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x05*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,M,v),
bc(M,M,M,M,M,M,M,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x06*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x07*/

bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,v,v,M,M,M),
bc(M,M,M,v,v,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),	/*0x08*/

bc(v,v,M,M,M,v,v,v),
bc(v,M,v,v,v,M,v,v),
bc(M,v,v,v,v,v,M,v),
bc(M,v,v,v,v,v,M,v),
bc(M,v,v,v,v,v,M,v),
bc(v,M,v,v,v,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x09*/

bc(M,M,v,v,v,M,M,M),
bc(M,v,M,M,M,v,M,M),
bc(v,M,M,M,M,M,v,M),
bc(v,M,M,M,M,M,v,M),
bc(v,M,M,M,M,M,v,M),
bc(M,v,M,M,M,v,M,M),
bc(M,M,v,v,v,M,M,M),
bc(M,M,M,M,M,M,M,M),	/*0x0a*/

bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,M,v,M),
bc(v,M,M,M,M,v,v,M),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),	/*0x0b*/

bc(v,v,M,M,M,v,v,v),
bc(v,M,v,v,v,M,v,v),
bc(v,M,v,v,v,M,v,v),
bc(v,M,v,v,v,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,M,M,M,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x0c*/

bc(v,v,M,M,v,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),	/*0x0d*/

bc(v,v,M,M,M,M,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,M,M,M,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,v,v,M,v,v),
bc(M,M,M,v,v,M,v,v),
bc(M,M,v,M,M,M,v,v),
bc(v,v,v,M,M,v,v,v),	/*0x0e*/

bc(v,v,v,M,v,v,v,v),
bc(v,M,v,M,v,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(M,M,M,v,M,M,M,v),
bc(v,v,M,M,M,v,v,v),
bc(v,M,v,M,v,M,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x0f*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,M,M,M,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x10*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x11*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x12*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x13*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,M,M,M,M),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x14*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x15*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x16*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x17*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,M,M,M,M,M),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x18*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),	/*0x19*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x1a*/

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x1b*/

bc(M,v,v,v,v,v,v,M),
bc(v,M,v,v,v,v,M,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,M,v,v,v,v,M,v),
bc(M,v,v,v,v,v,v,M),	/*0x1c*/

bc(v,v,v,v,v,v,v,M),
bc(v,v,v,v,v,v,M,v),
bc(v,v,v,v,v,M,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),	/*0x1d*/

bc(M,v,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,v,M,v,v),
bc(v,v,v,v,v,v,M,v),
bc(v,v,v,v,v,v,v,M),	/*0x1e*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x1f*/

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x20 ' ' */

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x21 '!' */

bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x22 '"' */

bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x23 '#' */

bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x24 '$' */

bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x25 '%' */

bc(v,M,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x26 '&' */

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x27 ''' */

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x28 '(' */

bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x29 ')' */

bc(v,v,M,v,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x2a '*' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x2b '+' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),	/*0x2c ',' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x2d '-' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x2e '.' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x2f '/' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x30 '0' */

bc(v,v,M,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x31 '1' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x32 '2' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x33 '3' */

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x34 '4' */

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x35 '5' */

bc(v,v,M,M,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x36 '6' */

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x37 '7' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x38 '8' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x39 '9' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x3a ':' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),	/*0x3b ';' */

bc(v,v,v,M,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x3c '<' */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x3d '=' */

bc(M,M,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x3e '>' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x3f '?' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x40 '@' */

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x41 'A' */

bc(M,M,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x42 'B' */

bc(v,v,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x43 'C' */

bc(M,M,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x44 'D' */

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x45 'E' */

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x46 'F' */

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x47 'G' */

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/*0x48 'H' */

bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,M,v,M,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,M,v,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),

bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,v,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x7c

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x7d

bc(M,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x7e

bc(v,M,v,v,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x7f

#if 0// (0) (0x80 ... 0xff)
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x80

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),	// 0x81

bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	// 0x82

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,M,M,v,v),
bc(v,v,v,M,v,v,M,v),
bc(v,M,M,M,M,M,M,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,M,M,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,M,M,M,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,M,M,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,M,M,M,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,M,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(M,M,M,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),

bc(v,v,v,M,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,v,v,v,M,v),
bc(v,M,v,M,M,M,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,v,M,M,M,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,M,v,v),

bc(v,v,v,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,M,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,v,M,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,M,v,M,v,v),
bc(M,v,v,v,v,M,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,v,M,M,M,v,v),

bc(M,v,v,v,v,M,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,M,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,v,M,M,M,M,v,v),
bc(v,v,v,v,M,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,M,v,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,M,v,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,M,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(M,M,M,v,M,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),

bc(M,M,v,v,v,v,v,v),
bc(v,M,v,v,v,M,v,v),
bc(M,M,v,v,M,v,v,v),
bc(v,M,v,M,v,M,v,v),
bc(M,M,M,v,M,M,v,v),
bc(v,M,v,M,v,M,v,v),
bc(M,v,v,M,M,M,M,v),
bc(v,v,v,v,v,M,v,v),

bc(v,v,v,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,M,M,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,M,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),

bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),

bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,M,M,v,v),
bc(v,v,M,M,M,M,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),

bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),

bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,v,v),

bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,M,M),

bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),
bc(v,v,M,M,M,M,M,M),

bc(v,v,v,M,v,v,v,M),
bc(v,v,M,v,v,v,M,v),
bc(v,M,v,v,v,M,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,M,v,v,v,M),
bc(v,v,M,v,v,v,M,v),
bc(v,M,v,v,v,M,v,v),
bc(M,v,v,v,M,v,v,v),

bc(M,v,v,v,M,v,v,v),
bc(v,M,v,v,v,M,v,v),
bc(v,v,M,v,v,v,M,v),
bc(v,v,v,M,v,v,v,M),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,v,v,M,v,v),
bc(v,v,M,v,v,v,M,v),
bc(v,v,v,M,v,v,v,M),

bc(M,M,M,M,M,M,M,v),
bc(v,M,M,M,M,M,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,M,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,M,M,M,M,M,v,v),
bc(M,M,M,M,M,M,M,v),

bc(M,v,v,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,v,M,M,M),
bc(v,v,v,v,v,v,M,M),
bc(v,v,v,v,v,v,v,M),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,M,M,M),
bc(v,M,M,M,M,M,M,v),
bc(v,v,M,M,M,M,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,M,M,M,M,v,v),
bc(v,M,M,M,M,M,M,v),
bc(M,M,M,M,M,M,M,M),

bc(M,v,v,v,v,v,v,M),
bc(M,M,v,v,v,v,M,M),
bc(M,M,M,v,v,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,v,v,M,M,M),
bc(M,M,v,v,v,v,M,M),
bc(M,v,v,v,v,v,v,M),

bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),

bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),

bc(v,v,M,M,v,v,M,M),
bc(v,v,M,M,v,v,M,M),
bc(M,M,v,v,M,M,v,v),
bc(M,M,v,v,M,M,v,v),
bc(v,v,M,M,v,v,M,M),
bc(v,v,M,M,v,v,M,M),
bc(M,M,v,v,M,M,v,v),
bc(M,M,v,v,M,M,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),

bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),
bc(M,M,M,M,v,v,v,v),

bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),
bc(v,v,v,v,M,M,M,M),

bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(M,M,M,M,M,M,M,M),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,M,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(M,v,v,M,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,M,v,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,M,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,M,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(M,v,M,v,M,v,v,v),
bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,M,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,M,M,M,v,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(M,v,v,v,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,M,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(M,M,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,M,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(M,v,v,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,M,v,v,v,v),
bc(v,v,M,v,M,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),

bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(M,M,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,M,v,v,M,v,v),
bc(v,v,v,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,M,M,M,M,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(v,v,M,M,M,M,M,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,M,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),

bc(M,v,M,v,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,M,v,M,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/* 0xfc */

bc(v,M,v,v,v,v,v,v),
bc(M,v,M,v,v,v,v,v),
bc(v,v,M,v,v,v,v,v),
bc(v,M,v,v,v,v,v,v),
bc(M,M,M,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/* 0xfd */

bc(v,v,v,v,v,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,M,M,M,v,v,v),
bc(v,v,v,v,v,v,v,v),	/* 0xfe */

bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),
bc(v,v,v,v,v,v,v,v),	/* 0xff */

#endif// (0) (0x80 ... 0xff)
};
#undef M
#undef v
#undef bc
